#!/usr/bin/python

import imaplib
import os
obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
obj.login( os.environ.get('gmail_address'), os.environ.get('gmail_password') ) # write your email and password
obj.select()
print(len(obj.search(None, 'UnSeen')[1][0].split()))
