#!/bin/bash
scrot '/tmp/scrot.png' -e 'convert -blur 0x2 $f /tmp/lockbg.png'
convert -gravity center -composite /tmp/lockbg.png /home/amyth/.config/img/lock.png /tmp/lockfinal.png
i3lock -i /tmp/lockfinal.png
rm /tmp/lockfinal.png /tmp/lockbg.png /tmp/scrot.png
