#!/bin/bash
for i in .config/*
do 
	[ -d ~/.config/$i ] && rm -r ~/.config/$i
	ln -sf /media/`whoami`/data/workspace/dotfiles/$i ~/.config
done

#conky
#if [ -d ~/.conky ]
#	then rm -r ~/.conky
#	
#fi
#ln -sf /media/`whoami`/data/workspace/dotfiles/.config/conky ~/.conky

#mpd
mkdir -p ~/.config/mpd/playlists
touch ~/.config/mpd/log
touch ~/.config/mpd/mpd.db
touch ~/.config/mpd/pid
touch ~/.config/mpd/state

#i3 reload
i3-msg restart
i3-msg restart
