#!/bin/bash
for i in .config/*
do
       #echo $i
       [ -d ~/$i ] && rm -r ~/$i
       ln -sf /media/`whoami`/data/home/workspace/dotfiles/$i ~/.config
done

#conky
#if [ -d ~/.conky ]
#	then rm -r ~/.conky
#	
#fi
#ln -sf /media/`whoami`/data/workspace/dotfiles/.config/conky ~/.conky

#mpd
[ -d ~/.config/mpd ] && rm -r ~/.config/mpd
mkdir -p ~/.config/mpd/playlists
touch ~/.config/mpd/log
touch ~/.config/mpd/mpd.db
touch ~/.config/mpd/pid
touch ~/.config/mpd/state

#i3 reload
i3-msg restart
i3-msg restart
