#! /bin/bash
	
	# replace with your mpd music path
	MUSIC_DIR=/media/amyth/data/home/Music
	COVER=~/.mpd/cover.png
    
{	album="$(mpc --format %album% current)"
    file="$(mpc --format %file% current)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    #covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    #src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER"
    ffmpeg -i "$MUSIC_DIR/$file" $COVER
    # cp "$src" "$COVER"
} &
