#!/bin/bash
for i in cava compton dunst i3 mpd ncmpcpp polybar ranger scripts x zsh
do 
	cp -Rf $i ~/.config/
done

#need to modify mpd config
user=`whoami`
sed -i "s|amit|$user|g" ~/.config/mpd/mpd.conf

#i3 reload
i3-msg restart
i3-msg restart
