#!/bin/sh

# just a command to launch urxvt with pikachu background
# replace zsh with bash if are using bash
urxvt -hold -pixmap ~/.config/img/pikachu.jpg \
-e fish \
-c "printf '\033]708;rgb:f7/de/82\007'; fish" # clean up the terminal padding
