#!/bin/zsh

# just a command to launch urxvt with squirtle background
# replace zsh with bash if are using bash
urxvt -hold -pixmap ~/.config/img/squirtle.jpg \
-e zsh \
-c "printf '\033]708;rgb:84/c1/d4\007'; zsh" # clean up the terminal padding
